/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Ciro
 * Created: May 25, 2016
 */



CREATE TABLE Compratore (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(128),
        cognome VARCHAR(128),
        username  VARCHAR(128),
        password VARCHAR(128)
);

CREATE TABLE Venditore (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR(128),
        cognome VARCHAR(128),
        username  VARCHAR(128),
        password VARCHAR(128)
        
);

CREATE TABLE Oggetti (
        venditoreId INTEGER,
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        quantita INTEGER,
        nome VARCHAR(128),
        prezzo DOUBLE,
        url VARCHAR(128),
        descrizione VARCHAR(128)
        FOREIGN KEY (venditoreId) REFERENCES venditore(id)
        
);

CREATE TABLE Account (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        soldi DOUBLE
);

INSERT INTO Compratore (userId, nome, cognome, username, password)
VALUES (3, "Gigi", "Mereu", "Gimmy", "aa"),
       (4, "gabriele", "piras", "eldiablo", "bb");

INSERT INTO Venditore (userId, nome, cognome, username, password)
VALUES (1, "Babbo", "Natale", "babbo", "cc"),
       (2, "Andrea", "Casti", "aereo", "plano");

INSERT INTO Oggetti (id, venditoreId, quantita, nome, prezzo, url, descrizione,)
VALUES (7, 1, "Set di chips", 149, "./img/chips.jpg", "generico"),
       (0, 1, "Donna dell'est", 0, "./img/donne.jpg", "generico"),
       (3, 1, "Mazzo di carte", 349, "./img/cards.jpg", "generico"),
       (1, 2, "Tavolo da poker", 399, "./img/tavolo.jpg", "generico"),
       (5, 2, "Pistola contro i bari", 799, "./img/pistola.jpg", "generico"),
       (2, 2, "Slot machine", 999, "./img/slot.jpg", "generico");

INSERT INTO Account (id, soldi)
VALUES (3, 1500),
       (2, 120),
       (4, 15000),
       (1, 50);
